-- Spring Data JPAのSalesOrderとSalesOrderLineをSQLで表した検証用スクリプト
-- 対象: H2 2.x（このプロジェクトのPostgreSQL互換モードでも実行可能）
-- 注意: 既存テーブルを削除するため、検証専用DBで実行すること。

DROP TABLE IF EXISTS sales_order_lines;
DROP TABLE IF EXISTS sales_orders;

-- SalesOrderエンティティ
CREATE TABLE sales_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number VARCHAR(255)
);

-- SalesOrderLineエンティティ
-- sales_order_idが@ManyToOneの外部キーに対応する。
-- Java側でline.assignTo(null)を許容するモデルなのでNULLを許可する。
CREATE TABLE sales_order_lines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_code VARCHAR(255),
    sales_order_id BIGINT,
    CONSTRAINT fk_sales_order_lines_sales_order
        FOREIGN KEY (sales_order_id) REFERENCES sales_orders (id)
);

-- 注文SO-001と二つの明細を用意する。
INSERT INTO sales_orders (id, order_number)
VALUES (1, 'SO-001');

INSERT INTO sales_order_lines (id, product_code, sales_order_id)
VALUES
    (1, 'PEN', 1),
    (2, 'NOTE', 1);

-- 初期状態:
-- order_line_count = 2、total_line_count = 2
SELECT COUNT(*) AS order_line_count
FROM sales_order_lines
WHERE sales_order_id = 1;

SELECT COUNT(*) AS total_line_count
FROM sales_order_lines;

-- ================================================================
-- orphanRemoval = false相当
-- ================================================================
-- 親コレクションからPENを外し、子側の親参照をnullにする操作は、
-- SQLでは外部キーをNULLへ更新する処理に相当する。
-- 子レコード自体は削除されない。
SET AUTOCOMMIT FALSE;

UPDATE sales_order_lines
SET sales_order_id = NULL
WHERE sales_order_id = 1
  AND product_code = 'PEN';

-- order_line_count = 1
SELECT COUNT(*) AS order_line_count
FROM sales_order_lines
WHERE sales_order_id = 1;

-- total_line_count = 2
SELECT COUNT(*) AS total_line_count
FROM sales_order_lines;

-- PENは残り、sales_order_idだけがNULLになる。
SELECT id, product_code, sales_order_id
FROM sales_order_lines
WHERE product_code = 'PEN';

-- 次の検証で同じ初期データを使うため、UPDATEを取り消す。
ROLLBACK;
SET AUTOCOMMIT TRUE;

-- ================================================================
-- orphanRemoval = true相当
-- ================================================================
-- orphanRemovalはORMのライフサイクル設定であり、DDLの指定ではない。
-- 同じ結果をSQLで直接表す場合は、関連から外す子をDELETEする。
SET AUTOCOMMIT FALSE;

DELETE FROM sales_order_lines
WHERE sales_order_id = 1
  AND product_code = 'PEN';

-- order_line_count = 1
SELECT COUNT(*) AS order_line_count
FROM sales_order_lines
WHERE sales_order_id = 1;

-- total_line_count = 1
SELECT COUNT(*) AS total_line_count
FROM sales_order_lines;

-- pen_row_count = 0
SELECT COUNT(*) AS pen_row_count
FROM sales_order_lines
WHERE product_code = 'PEN';

COMMIT;
SET AUTOCOMMIT TRUE;

-- ON DELETE CASCADEは、親注文をDELETEしたときに子明細も削除する機能である。
-- 親を残したままコレクションから一明細だけ外すorphanRemovalとは異なる。
